version: '3.7'

services:
  # service:
  #   build: .
  #   volumes:
  #     - .:/srv/service
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  db:
    image: ${DATABASE_TYPE}:${DATABASE_VERSION}
    command: mysqld --sql_mode=""
    restart: always
    volumes:
      - ./settings/mysql/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
