-- TODO: Get info from .env --
CREATE DATABASE IF NOT EXISTS ${DATABASE};
SET PASSWORD FOR ${MYSQL_USER}@'%' = PASSWORD(${MYSQL_PASSWORD});
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON ${DATABASE}.* TO ${MYSQL_USER}@'%' identified by ${MYSQL_PASSWORD};
FLUSH PRIVILEGES;
